version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
 #     - "/etc/timezone:/etc/timezone:ro"
 #     - "/etc/localtime:/etc/localtime:ro"      
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      MINIO_ACCESS_KEY: YOUR_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: YOUR_MINIO_SECRET_KEY
    command: server /data

  image-resizer:
    image: millken/nginx-image-resizer
    container_name: image-resizer
    ports:
      - 8002:80
    volumes:
      - cache-data:/data
#      - "/etc/timezone:/etc/timezone:ro"
#      - "/etc/localtime:/etc/localtime:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    environment:
      IMAGE_HOST: http://minio:9000
      NGINX_HOST: localhost

volumes:
  minio-data:
  cache-data:
